# goapp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: goapp    
  template:
    metadata:
      labels:
        app.kubernetes.io/name: goapp
    spec:
      containers:
      - image: docker.io/gauravkr19/goapp:web
        name: goapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 500m
            memory: 1Gi          
---
apiVersion: v1
kind: Service
metadata:
  name: goapp
spec:
  ports:
  - name: http
    port: 8089
    targetPort: 8080
  selector:
    app.kubernetes.io/name: goapp